spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
  jpa:
    show-sql: true
app:
  data:
      origin-url: "http://api.gios.gov.pl/pjp-api/rest"
      station-endpoint: "/station/findAll/"
      #in days
      expiration-stations: 30
      expiration-sensors: 30
      #in minutes
      expiration-summary: 30
      expiration-data: 30

